services:
  - type: web
    name: giramondo
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FLOW_API_KEY
        value: 1F116A19-C5A0-4EDE-AC86-76A0765L058C
      - key: FLOW_SECRET
        value: 71620f26c763b7565f9afe89f2777872f44348eb
      - key: BASE_URL
        value: https://giramondo.onrender.com
      - key: GMAIL_APP_PASSWORD
        sync: false
